[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "scalingOIII"
version = "0.1.0"
description = "A Python module for MCMC-based [OIII] scaling analysis for optical spectra of AGNs"
authors = [
  { name = "Tathagata Saha"}
]

dependencies = ["numpy",  "scipy", "emcee", "matplotlib", "corner"]

[tool.setuptools.packages.find]
where = ["."]
